export const X_OAUTH_SCOPES = [
  'tweet.read',
  'tweet.write',
  'tweet.moderate.write',
  'users.read',
  'offline.access',
  'like.read',
  'like.write',
  'follows.read',
  'follows.write',
  'bookmark.read',
  'bookmark.write',
  'list.read',
  'list.write',
  'block.read',
  'block.write',
  'mute.read',
  'mute.write',
  'space.read',
  'dm.read',
  'dm.write',
  'media.write',
] as const

export type XOAuthScope = (typeof X_OAUTH_SCOPES)[number]

export const X_OAUTH_SCOPE_CATALOG = [
  { scope: 'tweet.read', label: 'Read posts' },
  { scope: 'tweet.write', label: 'Post and manage posts' },
  {
    scope: 'tweet.moderate.write',
    label: 'Hide and unhide replies to your posts',
  },
  { scope: 'users.read', label: 'Read user profiles' },
  { scope: 'offline.access', label: 'Stay connected offline' },
  { scope: 'like.read', label: 'Read likes' },
  { scope: 'like.write', label: 'Like and unlike posts' },
  { scope: 'follows.read', label: 'Read follows' },
  { scope: 'follows.write', label: 'Follow and unfollow accounts' },
  { scope: 'bookmark.read', label: 'Read bookmarks' },
  { scope: 'bookmark.write', label: 'Manage bookmarks' },
  { scope: 'list.read', label: 'Read lists' },
  { scope: 'list.write', label: 'Create and manage lists' },
  { scope: 'block.read', label: 'Read blocked accounts' },
  { scope: 'block.write', label: 'Block and unblock accounts' },
  { scope: 'mute.read', label: 'Read muted accounts' },
  { scope: 'mute.write', label: 'Mute and unmute accounts' },
  { scope: 'space.read', label: 'Read Spaces' },
  { scope: 'dm.read', label: 'Read direct messages' },
  { scope: 'dm.write', label: 'Send and manage direct messages' },
  { scope: 'media.write', label: 'Upload media' },
] as const satisfies ReadonlyArray<{ label: string; scope: XOAuthScope }>
