import { readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'

const DOCS_DIRECTORY_NAME = 'docs'
const INDEX_FILE_NAME = 'index.md'
const MARKDOWN_EXTENSION = '.md'
const MAX_CONTENT_MARKDOWN_LINES = 30
const ROOT_LINKS_PER_LINE = 3
const GENERATED_NOTICE =
  '<!-- This file is generated by scripts/docs-index.ts. Run `pnpm docs:index` to update. -->'
const HEADING_PATTERN = /^#\s+(.+?)\s*$/mu
const LINE_BREAK_PATTERN = /\r\n|\r|\n/u
const WORD_SEPARATOR_PATTERN = /[-_]+/u
const ACRONYMS = new Set([
  'adr',
  'api',
  'cli',
  'db',
  'otp',
  'sdk',
  'seo',
  'ui',
  'url',
])

type RunMode = 'check' | 'write'

interface ScriptOptions {
  help: boolean
  mode: RunMode
}

interface MarkdownFile {
  absolutePath: string
  lineCount: number
  name: string
  relativePath: string
  title: string
}

interface DocsDirectory {
  absolutePath: string
  markdownFiles: MarkdownFile[]
  name: string
  relativePath: string
  subdirectories: DocsDirectory[]
}

interface GeneratedIndex {
  absolutePath: string
  content: string
  relativePath: string
}

interface LineLengthViolation {
  lineCount: number
  relativePath: string
}

interface FolderLink {
  name: string
  target: string
  title: string
}

function renderFolderLink(folderLink: FolderLink): string {
  return `[${escapeMarkdownLinkText(folderLink.title)}](${folderLink.target})`
}

function chunkItems<T>(items: T[], size: number): T[][] {
  const chunks: T[][] = []

  for (let index = 0; index < items.length; index += size) {
    chunks.push(items.slice(index, index + size))
  }

  return chunks
}

function printUsage(): void {
  console.log(`Generate and validate documentation indexes.

Usage:
  pnpm docs:index
  pnpm docs:check
  node --experimental-strip-types scripts/docs-index.ts [--write|--check]

Options:
  --write       Regenerate docs index files, then validate content line limits.
  --check       Validate indexes are current and enforce content line limits.
  --help, -h    Show this help text.
`)
}

function parseArgs(argv: string[]): ScriptOptions {
  const options: ScriptOptions = {
    help: false,
    mode: 'write',
  }

  for (const arg of argv) {
    switch (arg) {
      case '--write':
        options.mode = 'write'
        break
      case '--check':
        options.mode = 'check'
        break
      case '--help':
      case '-h':
        options.help = true
        break
      default:
        throw new Error(`Unknown argument: ${arg}`)
    }
  }

  return options
}

function isMarkdownFile(fileName: string): boolean {
  return path.extname(fileName).toLowerCase() === MARKDOWN_EXTENSION
}

function isIndexFile(fileName: string): boolean {
  return fileName.toLowerCase() === INDEX_FILE_NAME
}

function toPosixPath(filePath: string): string {
  return filePath.split(path.sep).join('/')
}

function toMarkdownLinkTarget(filePath: string): string {
  return toPosixPath(filePath).split('/').map(encodeURIComponent).join('/')
}

function countLines(content: string): number {
  if (!content) {
    return 0
  }

  const lines = content.split(LINE_BREAK_PATTERN)
  if (content.endsWith('\n') || content.endsWith('\r')) {
    return lines.length - 1
  }

  return lines.length
}

function titleCaseWord(word: string): string {
  if (!word) {
    return word
  }

  if (ACRONYMS.has(word.toLowerCase())) {
    return word.toUpperCase()
  }

  return `${word.slice(0, 1).toUpperCase()}${word.slice(1)}`
}

function titleFromPathSegment(segment: string): string {
  return segment
    .split(WORD_SEPARATOR_PATTERN)
    .filter(Boolean)
    .map(titleCaseWord)
    .join(' ')
}

function fallbackTitleFromFileName(fileName: string): string {
  return titleFromPathSegment(path.basename(fileName, MARKDOWN_EXTENSION))
}

function extractTitle(content: string, fileName: string): string {
  const headingMatch = content.match(HEADING_PATTERN)
  if (headingMatch?.[1]) {
    return headingMatch[1].trim()
  }

  return fallbackTitleFromFileName(fileName)
}

function escapeMarkdownLinkText(text: string): string {
  return text.replaceAll('[', '\\[').replaceAll(']', '\\]')
}

function compareByName(
  left: { name: string },
  right: { name: string }
): number {
  return left.name.localeCompare(right.name)
}

function compareByRelativePath(
  left: { relativePath: string },
  right: { relativePath: string }
): number {
  return left.relativePath.localeCompare(right.relativePath)
}

function nonIndexMarkdownFiles(directory: DocsDirectory): MarkdownFile[] {
  return directory.markdownFiles.filter((file) => !isIndexFile(file.name))
}

function collectNonIndexMarkdownFiles(
  directory: DocsDirectory
): MarkdownFile[] {
  const files: MarkdownFile[] = []

  for (const file of nonIndexMarkdownFiles(directory)) {
    files.push(file)
  }

  for (const subdirectory of directory.subdirectories) {
    const subdirectoryFiles = collectNonIndexMarkdownFiles(subdirectory)
    for (const file of subdirectoryFiles) {
      files.push(file)
    }
  }

  return files.sort(compareByRelativePath)
}

function shouldGenerateIndex(
  directory: DocsDirectory,
  docsRoot: string
): boolean {
  return (
    directory.absolutePath === docsRoot ||
    collectNonIndexMarkdownFiles(directory).length > 1
  )
}

function resolveFolderLink(
  directory: DocsDirectory,
  subdirectory: DocsDirectory,
  docsRoot: string
): FolderLink | null {
  const subdirectoryFiles = collectNonIndexMarkdownFiles(subdirectory)
  if (subdirectoryFiles.length === 0) {
    return null
  }

  const targetPath = shouldGenerateIndex(subdirectory, docsRoot)
    ? path.join(subdirectory.absolutePath, INDEX_FILE_NAME)
    : subdirectoryFiles[0].absolutePath

  return {
    name: subdirectory.name,
    target: toMarkdownLinkTarget(
      path.relative(directory.absolutePath, targetPath)
    ),
    title: titleFromPathSegment(subdirectory.name),
  }
}

function collectFolderLinks(
  directory: DocsDirectory,
  docsRoot: string
): FolderLink[] {
  const folderLinks: FolderLink[] = []

  for (const subdirectory of directory.subdirectories) {
    const folderLink = resolveFolderLink(directory, subdirectory, docsRoot)
    if (folderLink) {
      folderLinks.push(folderLink)
    }
  }

  return folderLinks.sort(compareByName)
}

function renderDirectoryTitle(directory: DocsDirectory): string {
  if (!directory.relativePath) {
    return 'Documentation Index'
  }

  return `${titleFromPathSegment(directory.name)} Index`
}

function renderIndex(directory: DocsDirectory, docsRoot: string): string {
  const lines = [
    GENERATED_NOTICE,
    '',
    `# ${renderDirectoryTitle(directory)}`,
    '',
  ]
  const folderLinks = collectFolderLinks(directory, docsRoot)
  const documents = nonIndexMarkdownFiles(directory).sort(compareByRelativePath)

  if (folderLinks.length > 0) {
    if (directory.relativePath) {
      lines.push('## Folders', '')
      for (const folderLink of folderLinks) {
        lines.push(`- ${renderFolderLink(folderLink)}`)
      }
    } else {
      for (const chunk of chunkItems(folderLinks, ROOT_LINKS_PER_LINE)) {
        lines.push(`- ${chunk.map(renderFolderLink).join(' · ')}`)
      }
    }
    lines.push('')
  }

  if (documents.length > 0) {
    lines.push('## Documents', '')
    for (const document of documents) {
      lines.push(
        `- [${escapeMarkdownLinkText(document.title)}](${toMarkdownLinkTarget(document.name)})`
      )
    }
    lines.push('')
  }

  if (folderLinks.length === 0 && documents.length === 0) {
    lines.push('No documents found.', '')
  }

  return `${lines.join('\n').trimEnd()}\n`
}

async function readMarkdownFile(
  absolutePath: string,
  docsRoot: string,
  name: string
): Promise<MarkdownFile> {
  const content = await readFile(absolutePath, 'utf8')
  return {
    absolutePath,
    lineCount: countLines(content),
    name,
    relativePath: toPosixPath(path.relative(docsRoot, absolutePath)),
    title: extractTitle(content, name),
  }
}

async function readDocsDirectory(
  absolutePath: string,
  docsRoot: string
): Promise<DocsDirectory> {
  const entries = (await readdir(absolutePath, { withFileTypes: true })).sort(
    compareByName
  )
  const markdownFileEntries = entries.filter(
    (entry) => entry.isFile() && isMarkdownFile(entry.name)
  )
  const subdirectoryEntries = entries.filter((entry) => entry.isDirectory())
  const markdownFiles = await Promise.all(
    markdownFileEntries.map((entry) =>
      readMarkdownFile(
        path.join(absolutePath, entry.name),
        docsRoot,
        entry.name
      )
    )
  )
  const subdirectories = await Promise.all(
    subdirectoryEntries.map((entry) =>
      readDocsDirectory(path.join(absolutePath, entry.name), docsRoot)
    )
  )

  return {
    absolutePath,
    markdownFiles,
    name: path.basename(absolutePath),
    relativePath: toPosixPath(path.relative(docsRoot, absolutePath)),
    subdirectories,
  }
}

function collectGeneratedIndexes(
  directory: DocsDirectory,
  docsRoot: string
): GeneratedIndex[] {
  const indexes: GeneratedIndex[] = []

  if (shouldGenerateIndex(directory, docsRoot)) {
    const absolutePath = path.join(directory.absolutePath, INDEX_FILE_NAME)
    indexes.push({
      absolutePath,
      content: renderIndex(directory, docsRoot),
      relativePath: toPosixPath(path.relative(docsRoot, absolutePath)),
    })
  }

  for (const subdirectory of directory.subdirectories) {
    const subdirectoryIndexes = collectGeneratedIndexes(subdirectory, docsRoot)
    for (const index of subdirectoryIndexes) {
      indexes.push(index)
    }
  }

  return indexes.sort(compareByRelativePath)
}

function collectExistingLineLengthViolations(
  directory: DocsDirectory
): LineLengthViolation[] {
  const violations: LineLengthViolation[] = []

  for (const file of directory.markdownFiles) {
    if (isIndexFile(file.name)) {
      continue
    }

    if (file.lineCount > MAX_CONTENT_MARKDOWN_LINES) {
      violations.push({
        lineCount: file.lineCount,
        relativePath: file.relativePath,
      })
    }
  }

  for (const subdirectory of directory.subdirectories) {
    const subdirectoryViolations =
      collectExistingLineLengthViolations(subdirectory)
    for (const violation of subdirectoryViolations) {
      violations.push(violation)
    }
  }

  return violations.sort(compareByRelativePath)
}

function isNotFoundError(error: unknown): boolean {
  if (!(error instanceof Error && 'code' in error)) {
    return false
  }

  return error.code === 'ENOENT'
}

async function findOutdatedIndexes(
  indexes: GeneratedIndex[]
): Promise<GeneratedIndex[]> {
  const outdatedIndexes: GeneratedIndex[] = []

  for (const index of indexes) {
    let currentContent = ''
    try {
      currentContent = await readFile(index.absolutePath, 'utf8')
    } catch (error: unknown) {
      if (!isNotFoundError(error)) {
        throw error
      }
    }

    if (currentContent !== index.content) {
      outdatedIndexes.push(index)
    }
  }

  return outdatedIndexes
}

async function writeIndexes(indexes: GeneratedIndex[]): Promise<void> {
  for (const index of indexes) {
    await writeFile(index.absolutePath, index.content, 'utf8')
  }
}

function reportLineLengthViolations(violations: LineLengthViolation[]): void {
  if (violations.length === 0) {
    return
  }

  console.error(
    `Non-index markdown files under docs must be ${MAX_CONTENT_MARKDOWN_LINES} lines or fewer.`
  )
  for (const violation of violations) {
    console.error(
      `- docs/${violation.relativePath}: ${violation.lineCount} lines`
    )
  }
}

function reportOutdatedIndexes(indexes: GeneratedIndex[]): void {
  if (indexes.length === 0) {
    return
  }

  console.error('Documentation indexes are out of date. Run `pnpm docs:index`.')
  for (const index of indexes) {
    console.error(`- docs/${index.relativePath}`)
  }
}

async function main(): Promise<void> {
  const options = parseArgs(process.argv.slice(2))
  if (options.help) {
    printUsage()
    return
  }

  const repoRoot = process.cwd()
  const docsRoot = path.join(repoRoot, DOCS_DIRECTORY_NAME)
  const docsDirectory = await readDocsDirectory(docsRoot, docsRoot)
  const indexes = collectGeneratedIndexes(docsDirectory, docsRoot)
  const lineLengthViolations =
    collectExistingLineLengthViolations(docsDirectory)

  if (options.mode === 'write') {
    await writeIndexes(indexes)
    console.log(`Generated ${indexes.length} documentation index file(s).`)
  } else {
    const outdatedIndexes = await findOutdatedIndexes(indexes)
    reportOutdatedIndexes(outdatedIndexes)
    if (outdatedIndexes.length > 0) {
      process.exitCode = 1
    }
  }

  reportLineLengthViolations(lineLengthViolations)
  if (lineLengthViolations.length > 0) {
    process.exitCode = 1
  }
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error)
  console.error(`Failed: ${message}`)
  process.exitCode = 1
})
