import {
  account,
  agent,
  agentChannelBindings,
  agentEvents,
  agentTokenUsage,
  agentTools,
  budgetRule,
  channelInstallations,
  channelThreadConversations,
  chatConversation,
  chatMessage,
  session,
  user,
  userConnections,
  verification,
  waitlistEntry,
} from './schema'

export const dbSchema = {
  user,
  session,
  account,
  verification,
  agent,
  agentEvents,
  chatConversation,
  chatMessage,
  userConnections,
  agentTools,
  budgetRule,
  agentTokenUsage,
  channelInstallations,
  agentChannelBindings,
  channelThreadConversations,
  waitlistEntry,
} as const
